# Generated by Django 4.2.23 on 2025-08-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=50),
        ),
    ]
