# Generated by Django 4.2.23 on 2025-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('set', 'Set')], default='top', max_length=50),
        ),
    ]
